
### users.getAll
GET http://localhost:8080/users.getAll
X-login: vasya
X-password: secret

### users.getById
GET http://localhost:8080/users.getById?id=2
X-login: vasya
X-password: secret

### users.create
GET http://localhost:8080/users.create?login=sasha&password=password
X-login: vasya
X-password: secret

### users.delete
GET http://localhost:8080/users.deleteById?id=2
X-login: vasya
X-password: secret